/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Product {
  'id' : string,
  'status' : ProductStatus,
  'title' : string,
  'description' : string,
  'variants' : Array<ProductVariant>,
  'productType' : ProductType,
  'stock' : bigint,
  'vendorId' : string,
  'category' : string,
  'image' : [] | [Principal],
  'price' : bigint,
}
export type ProductStatus = { 'active' : null } |
  { 'inactive' : null };
export type ProductType = { 'service' : null } |
  { 'physical' : null } |
  { 'digital' : null };
export interface ProductVariant {
  'value' : string,
  'name' : string,
  'stockAdjustment' : bigint,
  'priceAdjustment' : bigint,
}
export interface Review {
  'id' : string,
  'title' : string,
  'body' : string,
  'storeId' : string,
  'createdAt' : bigint,
  'productId' : string,
  'rating' : bigint,
  'reviewer' : Principal,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StoreResponse {
  'id' : string,
  'contactInfo' : string,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'isActive' : boolean,
  'vendorId' : Principal,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WholesaleAccount {
  'id' : string,
  'status' : WholesaleAccountStatus,
  'applicant' : Principal,
  'taxId' : string,
  'createdAt' : bigint,
  'businessName' : string,
  'reviewedAt' : [] | [bigint],
  'reviewedBy' : [] | [Principal],
}
export type WholesaleAccountStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface WholesaleTier {
  'tierLabel' : string,
  'minQty' : bigint,
  'pricePerUnit' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProductToStore' : ActorMethod<[string, Product], undefined>,
  'addVariant' : ActorMethod<[string, string, ProductVariant], undefined>,
  'approveWholesaleAccount' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createStore' : ActorMethod<[string, string, string], StoreResponse>,
  'deleteReview' : ActorMethod<[string, string], undefined>,
  'deleteStoreProduct' : ActorMethod<[string, string], undefined>,
  'deleteVariant' : ActorMethod<[string, string, bigint], undefined>,
  'getAllStoreIds' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyWholesaleAccount' : ActorMethod<[], [] | [WholesaleAccount]>,
  'getProduct' : ActorMethod<[string, string], [] | [Product]>,
  'getProductRatingSummary' : ActorMethod<
    [string],
    {
      'averageRating' : number,
      'totalReviews' : bigint,
      'distribution' : Array<bigint>,
    }
  >,
  'getProductReviews' : ActorMethod<[string], Array<Review>>,
  'getStoresByVendor' : ActorMethod<[Principal], Array<StoreResponse>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWholesalePrice' : ActorMethod<[string, bigint], [] | [bigint]>,
  'getWholesaleTiers' : ActorMethod<[string], Array<WholesaleTier>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listStoreProducts' : ActorMethod<[string], Array<Product>>,
  'listWholesaleApplications' : ActorMethod<[], Array<WholesaleAccount>>,
  'registerWholesaleAccount' : ActorMethod<[string, string], undefined>,
  'rejectWholesaleAccount' : ActorMethod<[Principal], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setWholesaleTiers' : ActorMethod<
    [string, string, Array<WholesaleTier>],
    undefined
  >,
  'submitReview' : ActorMethod<
    [string, string, bigint, string, string],
    undefined
  >,
  'toggleStoreActive' : ActorMethod<[string], StoreResponse>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateStore' : ActorMethod<[string, string, string, string], StoreResponse>,
  'updateStoreProduct' : ActorMethod<[string, Product], undefined>,
  'updateVariant' : ActorMethod<
    [string, string, bigint, ProductVariant],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];