/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const ProductVariant = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
  'stockAdjustment' : IDL.Nat,
  'priceAdjustment' : IDL.Nat,
});
export const ProductType = IDL.Variant({
  'service' : IDL.Null,
  'physical' : IDL.Null,
  'digital' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'status' : ProductStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'variants' : IDL.Vec(ProductVariant),
  'productType' : ProductType,
  'stock' : IDL.Nat,
  'vendorId' : IDL.Text,
  'category' : IDL.Text,
  'image' : IDL.Opt(IDL.Principal),
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Time = IDL.Int;
export const StoreResponse = IDL.Record({
  'id' : IDL.Text,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'vendorId' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'storeId' : IDL.Text,
  'createdAt' : IDL.Int,
  'productId' : IDL.Text,
  'rating' : IDL.Nat,
  'reviewer' : IDL.Principal,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProductToStore' : IDL.Func([IDL.Text, Product], [], []),
  'addVariant' : IDL.Func([IDL.Text, IDL.Text, ProductVariant], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createStore' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [StoreResponse], []),
  'deleteReview' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteStoreProduct' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteVariant' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'getAllStoreIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProduct' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProductRatingSummary' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'averageRating' : IDL.Float64,
          'totalReviews' : IDL.Nat,
          'distribution' : IDL.Vec(IDL.Nat),
        }),
      ],
      ['query'],
    ),
  'getProductReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getStoresByVendor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StoreResponse)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listStoreProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'toggleStoreActive' : IDL.Func([IDL.Text], [StoreResponse], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateStore' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [StoreResponse],
      [],
    ),
  'updateStoreProduct' : IDL.Func([IDL.Text, Product], [], []),
  'updateVariant' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, ProductVariant],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const ProductVariant = IDL.Record({
    'value' : IDL.Text,
    'name' : IDL.Text,
    'stockAdjustment' : IDL.Nat,
    'priceAdjustment' : IDL.Nat,
  });
  const ProductType = IDL.Variant({
    'service' : IDL.Null,
    'physical' : IDL.Null,
    'digital' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'status' : ProductStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'variants' : IDL.Vec(ProductVariant),
    'productType' : ProductType,
    'stock' : IDL.Nat,
    'vendorId' : IDL.Text,
    'category' : IDL.Text,
    'image' : IDL.Opt(IDL.Principal),
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Time = IDL.Int;
  const StoreResponse = IDL.Record({
    'id' : IDL.Text,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'vendorId' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'storeId' : IDL.Text,
    'createdAt' : IDL.Int,
    'productId' : IDL.Text,
    'rating' : IDL.Nat,
    'reviewer' : IDL.Principal,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProductToStore' : IDL.Func([IDL.Text, Product], [], []),
    'addVariant' : IDL.Func([IDL.Text, IDL.Text, ProductVariant], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createStore' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [StoreResponse],
        [],
      ),
    'deleteReview' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteStoreProduct' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteVariant' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'getAllStoreIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProduct' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(Product)],
        ['query'],
      ),
    'getProductRatingSummary' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'averageRating' : IDL.Float64,
            'totalReviews' : IDL.Nat,
            'distribution' : IDL.Vec(IDL.Nat),
          }),
        ],
        ['query'],
      ),
    'getProductReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getStoresByVendor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StoreResponse)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listStoreProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'toggleStoreActive' : IDL.Func([IDL.Text], [StoreResponse], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateStore' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [StoreResponse],
        [],
      ),
    'updateStoreProduct' : IDL.Func([IDL.Text, Product], [], []),
    'updateVariant' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, ProductVariant],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };