/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface CartItem { 'productId' : string, 'quantity' : bigint }
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'total' : bigint,
  'paymentStatus' : PaymentStatus,
  'paymentSessionId' : [] | [string],
  'paymentHistory' : Array<PaymentStatus>,
  'customer' : Principal,
  'createdAt' : bigint,
  'statusHistory' : Array<OrderStatus>,
  'updatedAt' : bigint,
  'timestamp' : bigint,
  'shippingAddress' : string,
  'items' : Array<CartItem>,
  'paymentUrl' : [] | [string],
}
export type OrderStatus = { 'shipped' : null } |
  { 'canceled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'initiated' : null } |
  { 'completed' : null } |
  { 'awaiting_payment' : null } |
  { 'failed' : null };
export interface Product {
  'id' : string,
  'status' : ProductStatus,
  'title' : string,
  'description' : string,
  'productType' : ProductType,
  'stock' : bigint,
  'vendorId' : string,
  'category' : string,
  'image' : [] | [Principal],
  'price' : bigint,
}
export type ProductStatus = { 'active' : null } |
  { 'inactive' : null };
export type ProductType = { 'service' : null } |
  { 'physical' : null } |
  { 'digital' : null };
export interface SearchFilter {
  'sortBy' : [] | [
    { 'quantityDesc' : null } |
      { 'priceDesc' : null } |
      { 'priceAsc' : null }
  ],
  'productType' : [] | [ProductType],
  'category' : [] | [string],
  'keyword' : [] | [string],
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VendorProfile {
  'id' : string,
  'contact' : string,
  'logo' : [] | [Principal],
  'name' : string,
  'createdBy' : Principal,
  'description' : string,
  'approved' : boolean,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[string, bigint], undefined>,
  'approveVendorProfile' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createProduct' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      string,
      ProductType,
      bigint,
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'createVendorProfile' : ActorMethod<
    [string, string, string, [] | [ExternalBlob], string],
    undefined
  >,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[string], Order>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVendorProfile' : ActorMethod<[string], VendorProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'placeOrder' : ActorMethod<[string], string>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[SearchFilter], Array<Product>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      string,
      ProductType,
      bigint,
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'updateVendorProfile' : ActorMethod<
    [string, string, string, [] | [ExternalBlob], string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];